factor:
  class: factors.fundamental.valuation.valuation_pb_roe_residual.PB_ROE_Residual
  direction: -1

backtest:
  start_date: "2016-01-01"
  end_date: "2026-01-01"

grid:
  neutralization_methods: [size]
  top_k_list: [50]
  rebalance_freqs: [20]

benchmarks: [csi300, csi500, csi2000]

storage:
  eval_db_path: "../factor_eval_result/factor_eval.db"
